253438/253439 new structure
stone-payments/pos-mamba-sdk pull request #624
Opened 2021-03-31 19:42 UTC by JonasJs

2021-03-31 19:53 UTC, pedrosouza18 approved these changes

2021-03-31 20:37 UTC, didiraja commented on packages/pos/package.json
> +    "@mamba/app": "^2.33.3",
de volta para versao mais atual

2021-03-31 20:39 UTC, didiraja commented on packages/pos/simulator/view/pos/apps/Launcher.html
> +    background-color: $neutral300;
fix merge

2021-03-31 20:40 UTC, didiraja commented on packages/pos/simulator/view/pos/hardware/Keypad/index.html
> +      console.log(this.store.get())
remover console

2021-03-31 20:41 UTC, didiraja commented on packages/pos/simulator/view/pos/store.js
> +console.log(Registry.persistent.get().$Device.device);
remover console

2021-03-31 20:41 UTC, didiraja commented on packages/pos/simulator/view/pos/store.js
> +store.setDevice = model => {
mudar para `setPosModel`

2021-03-31 21:04 UTC, didiraja approved these changes

2021-04-01 14:08 UTC, jaikme requested changes

2021-04-01 14:08 UTC, jaikme commented on packages/pos/simulator/view/pos/apps/Launcher.html
> +<<<<<<< HEAD
💀

2021-04-01 17:04 UTC, merged