332194 flatlist update decorators
stone-payments/pos-mamba-sdk pull request #751
Opened 2021-11-17 22:41 UTC by didiraja

2021-11-18 14:44 UTC, AlessandroRodrigo requested changes

2021-11-18 14:44 UTC, AlessandroRodrigo commented on packages/components/Flatlist/FlatList.html
>      onupdate({changed, current}) {
O bloco de código do hook onupdate está bastante grande, conseguimos fazer um trabalho de organização e desacoplamento aqui.

2021-11-18 14:44 UTC, AlessandroRodrigo commented on packages/components/Flatlist/helpers.js
> + * @param obj
Falta de tipos nos parâmetros.

2021-11-18 14:44 UTC, AlessandroRodrigo commented on packages/components/Flatlist/components/decorator.html
> +   * @param position {prop}
Entendi que é uma documentação para o componente em si, apesar de não funcionar, podemos manter, mas com a tipagem certa das props. Ou podemos ter uma outra abordagem, que é começar a declarar no data() nossas props com valor inicial, que é recomendado pela documentação do framework.

2021-11-23 17:27 UTC, AlessandroRodrigo approved these changes

2021-11-23 17:28 UTC, JonasJs approved these changes

2021-11-23 17:32 UTC, merged