Update VerifiyModel logic
stone-payments/pos-mamba-sdk pull request #836
Opened 2022-12-20 18:38 UTC by didiraja

2022-12-21 21:41 UTC, jaikme requested changes

2022-12-21 21:41 UTC, jaikme commented on packages/utils/models.js
> +  return VerifyMethodOnSystemWrapper('hasOnlyTouch') || !_hasModelAtList(HAS_KEYBOARD);
Cara, o back não vai implementar o `hasOnlyTouch`, eles vão implementar só alguns, eu só sei que é o `hasSmallScreen`, e talvez um outro... tem que ver na thread la... Nesse caso aqui, eles falaram prá usar a negação do `hasKeyboard` mesmo. Então não adianta tentar chamar `VerifyMethodOnSystemWrapper('hasOnlyTouch')` que sempre vai dar errado.

```suggestion
  return !hasKeyboard();
```

2022-12-21 21:41 UTC, jaikme commented on packages/utils/models.js
> +  return !value;
Esse é difente, porque a gente não tem uma lista `HAS_PRINTER`. temos a `NO_PRINTER`, então tem que negar a lista estática, mantendo o valor do back.
(tirei a exclamação no value, e coloquei no `!_hasModelAtList`)


```suggestion
  /** negação explicada e comentada em hasNoTouch() */
  let value = VerifyMethodOnSystemWrapper('hasPrinter');

  if (!value) {
    value = !_hasModelAtList(NO_PRINTER);
  }

  return value;
```

2022-12-21 21:41 UTC, jaikme commented on packages/utils/models.js
> +  return VerifyMethodOnSystemWrapper('hasNoPrinter') || _hasModelAtList(NO_PRINTER);
```suggestion
  return !hasPrinter();
```

2022-12-21 21:47 UTC, jaikme requested changes

2022-12-21 21:47 UTC, jaikme commented on packages/utils/models.js
> +
Tive que mudar pra undefined, porque se o método do back retornar `false` `!value`, ele vai cair na lista estática, que é o que não queremos.

```suggestion
  if (!__POS__) return undefined;

```

2022-12-21 21:47 UTC, jaikme commented on packages/utils/models.js
> +  return null;
Tive que mudar pra undefined, porque se o método do back retornar false !value, ele vai cair na lista estática, que é o que não queremos.

```suggestion

  return undefined;
```

2022-12-21 21:47 UTC, jaikme commented on packages/utils/models.js
> +  return !value;
Tive que colocar `typeof value === 'undefined'`, porque se o método do back retornar `false`, o `if(!value)`, vai fazer cair na lista estática, que é o que não queremos.

2022-12-22 21:14 UTC, jaikme requested changes

2022-12-22 21:14 UTC, jaikme commented on packages/utils/models.js
> +  return !hasPrinter;
```suggestion
  return !hasPrinter();
```

`hasPrinter` é um método! Logo acima

2022-12-22 21:14 UTC, jaikme commented
Remove o comentário em pt-br ou passa pro ingles, pra não ficar salada de idiomas

2022-12-23 16:49 UTC, didiraja commented on packages/utils/models.js
> +  return !hasPrinter;
não acredito que dei esse mole

2022-12-23 20:05 UTC, jaikme approved these changes

2022-12-26 17:28 UTC, merged