Update repo_setup.py to handle missing .git folder
stone-payments/pos-mamba-sdk pull request #961
Opened 2024-06-04 02:20 UTC by danieldsdias

2024-06-04 11:31 UTC, wilsonevangelista commented on tools/repo_setup.py
> +                os.chdir(script_dir)
remover a pasta de `path` não pode acabar deletando trabalho de alguém, se der um repo_setup.py?

2024-06-04 12:18 UTC, FPTeixeira commented on tools/repo_setup.py
> +                os.chdir(script_dir)
Bom ponto... Talvez ali na linha 182 colocar um:

```
if force_remove_repo:
   remove_repo()
else:
   print("Backup any work in progress and add \"force remove repo\" (-f) param and try again.")
```

E o `force_remove_repo` ser resultado de um parâmetro `-f`

2024-06-04 12:21 UTC, FPTeixeira commented on tools/repo_setup.py
> +    print_color(message, RED)
Nice!

2024-06-04 12:21 UTC, FPTeixeira commented on tools/repo_setup.py
> +    print_color(message, RED)
```suggestion
def print_warning(message):
    print_color(message, YELLOW)

def print_error(message):
    print_color(message, RED)
```

2024-06-04 12:44 UTC, FPTeixeira commented on tools/repo_setup.py
> +                )
```suggestion
                print_error(
                    f"ERROR: No version, minimum_version, or branch was specified for the repository: {_path}"
                )
```

2024-06-04 12:44 UTC, FPTeixeira commented on tools/repo_setup.py
> +                print(f"{BLUE}Initalizing submodule {_path}{NC}")
```suggestion
                print_color(f"Initalizing submodule {_path}", BLUE)
```

2024-06-04 12:45 UTC, FPTeixeira commented on tools/repo_setup.py
> +                print(f"{BLUE}Updating submodule {_path}{NC}")
```suggestion
                print_color(f"Updating submodule {_path}", BLUE)
```

2024-06-04 12:45 UTC, FPTeixeira commented on tools/repo_setup.py
> +                print_error(f"Removing {_path} to try again...")
```suggestion
                print_warning(f"Removing {_path} to try again...")
```

2024-06-04 12:48 UTC, FPTeixeira requested changes
Revisado, deixei sugerâncias

2024-06-04 12:54 UTC, danieldsdias commented on tools/repo_setup.py
> +                os.chdir(script_dir)
Pra colocar um parâmetro pra apagar acho q não vale a pena então... O propósito era resolver sozinho o problema, se precisa de uma ação manual pra apagar então não adianta de nada pq qd falhar no pipeline ou no dia a dia como numa mudança de branch vai precisar ficar manualmente passando o -f.
Quanto a apagar o trabalho isso já acontece hj pq quando ele muda a branch e da reset então não faz diferença alguma.

2024-06-04 13:42 UTC, wilsonevangelista commented on tools/repo_setup.py
> +                os.chdir(script_dir)
Pô nem tinha percebido que atualmente tem isso, por isso quase perdi uma modificação, ainda bem que eu tinha uma branch!

2024-06-04 16:44 UTC, FPTeixeira commented on tools/repo_setup.py
> +                os.chdir(script_dir)
Dados os pontos, por mim fico OK de seguir sem o `-f`

2024-06-05 22:08 UTC, danieldsdias commented
@wilsonevangelista / @FPTeixeira botei o -f... Vejam se ficou do agrado dos senhores.

2024-06-05 22:26 UTC, FPTeixeira approved these changes

2024-06-05 22:26 UTC, merged